export default interface IShowDetails {
  id: number,
  name: string,
  permalink: string,
  description: string,
  description_source: string,
  start_date: string,
  end_date: string,
  country: string,
  status: string,
  runtime: number,
  network: string,
  youtube_link: string,
  image_path: string,
  image_thumbnail_path: string,
  rating: string,
  rating_count: string,
  genres: string[],
  pictures: string[],
}